import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

/**
 * Generate a medical report PDF
 * @param {Object} assessmentData - The assessment data from the AI analysis
 * @param {Object} userData - The user data
 * @param {string} outputPath - The path where the PDF should be saved
 * @returns {Promise<string>} - The path to the generated PDF
 */
export const generateMedicalReport = async (assessmentData, userData, outputPath) => {
  return new Promise((resolve, reject) => {
    try {
      // Create a document
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50
      });
      
      // Create write stream
      const writeStream = fs.createWriteStream(outputPath);
      doc.pipe(writeStream);
      
      // Header
      doc.image(path.join(process.cwd(), 'assets', 'logo.png'), 50, 45, { width: 50 })
        .fillColor('#2E7D32')
        .fontSize(20)
        .text('MedAid - Rural Healthcare Assistant', 110, 55)
        .fontSize(10)
        .text('AI-Powered Medical Triage for Rural Communities', 110, 80)
        .moveDown();
      
      // Horizontal line
      doc.strokeColor('#2E7D32')
        .lineWidth(2)
        .moveTo(50, 110)
        .lineTo(550, 110)
        .stroke();
      
      // Patient Information
      doc.fillColor('#000000')
        .fontSize(14)
        .text('Patient Information', 50, 130)
        .fontSize(10)
        .text(`Name: ${userData.name || 'N/A'}`, 50, 150)
        .text(`Age: ${userData.age || 'N/A'}`, 200, 150)
        .text(`Sex: ${userData.sex || 'N/A'}`, 350, 150)
        .text(`Date: ${new Date().toLocaleDateString()}`, 50, 170)
        .moveDown();
      
      // Assessment Results
      doc.fillColor('#000000')
        .fontSize(14)
        .text('Assessment Results', 50, 200)
        .fontSize(10);
      
      // Risk Level
      const riskLevel = assessmentData.risk_level || 'Unknown';
      let riskColor = '#000000';
      if (riskLevel.toLowerCase().includes('low')) riskColor = '#4CAF50';
      else if (riskLevel.toLowerCase().includes('moderate')) riskColor = '#FF9800';
      else if (riskLevel.toLowerCase().includes('high') || riskLevel.toLowerCase().includes('emergency')) riskColor = '#f44336';
      
      doc.fillColor(riskColor)
        .text(`Risk Level: ${riskLevel}`, 50, 220)
        .fillColor('#000000');
      
      // AI Reasoning
      if (assessmentData.reason) {
        doc.text('AI Reasoning:', 50, 240)
          .text(assessmentData.reason, 50, 255, { width: 500, align: 'justify' });
      }
      
      // Possible Conditions
      if (assessmentData.possible_conditions && assessmentData.possible_conditions.length > 0) {
        let yPos = 290;
        doc.text('Possible Conditions:', 50, yPos);
        yPos += 15;
        
        assessmentData.possible_conditions.forEach((condition, index) => {
          const confidence = Math.round((condition.confidence || 0) * 100);
          doc.text(`${index + 1}. ${condition.disease} (${confidence}%)`, 60, yPos);
          yPos += 15;
        });
        
        yPos += 10;
      }
      
      // Recommendations
      if (assessmentData.recommendations && assessmentData.recommendations.length > 0) {
        let yPos = 350;
        doc.text('Recommendations:', 50, yPos);
        yPos += 15;
        
        assessmentData.recommendations.forEach((rec, index) => {
          doc.text(`${index + 1}. ${rec}`, 60, yPos, { width: 500, align: 'justify' });
          yPos += 15;
        });
        
        yPos += 10;
      }
      
      // Emergency Notice
      if (riskLevel.toLowerCase().includes('high') || riskLevel.toLowerCase().includes('emergency')) {
        doc.fillColor('#f44336')
          .fontSize(12)
          .text('EMERGENCY NOTICE', 50, 450)
          .fontSize(10)
          .text('Please seek immediate medical attention. Do not delay in consulting a healthcare professional.', 50, 470, { width: 500, align: 'justify' })
          .fillColor('#000000');
      }
      
      // Footer
      doc.fillColor('#666666')
        .fontSize(8)
        .text('This report is generated by MedAid AI system and should not replace professional medical consultation.', 50, 700, { width: 500, align: 'center' })
        .text('For any medical emergency, please contact your local healthcare provider immediately.', 50, 715, { width: 500, align: 'center' })
        .text('Page 1 of 1', 50, 750);
      
      // Finalize PDF file
      doc.end();
      
      writeStream.on('finish', () => {
        resolve(outputPath);
      });
      
      writeStream.on('error', (err) => {
        reject(err);
      });
      
    } catch (error) {
      reject(error);
    }
  });
};

/**
 * Generate a buffer containing the PDF instead of saving to file
 * @param {Object} assessmentData - The assessment data from the AI analysis
 * @param {Object} userData - The user data
 * @returns {Promise<Buffer>} - A buffer containing the PDF data
 */
export const generateMedicalReportBuffer = async (assessmentData, userData) => {
  return new Promise((resolve, reject) => {
    try {
      // Create a document
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50
      });
      
      const chunks = [];
      
      doc.on('data', (chunk) => {
        chunks.push(chunk);
      });
      
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks);
        resolve(pdfBuffer);
      });
      
      doc.on('error', (err) => {
        reject(err);
      });
      
      // Header
      doc.fillColor('#2E7D32')
        .fontSize(20)
        .text('MedAid - Rural Healthcare Assistant', 50, 55)
        .fontSize(10)
        .text('AI-Powered Medical Triage for Rural Communities', 50, 80)
        .moveDown();
      
      // Horizontal line
      doc.strokeColor('#2E7D32')
        .lineWidth(2)
        .moveTo(50, 110)
        .lineTo(550, 110)
        .stroke();
      
      // Patient Information
      doc.fillColor('#000000')
        .fontSize(14)
        .text('Patient Information', 50, 130)
        .fontSize(10)
        .text(`Name: ${userData.name || 'N/A'}`, 50, 150)
        .text(`Age: ${userData.age || 'N/A'}`, 200, 150)
        .text(`Sex: ${userData.sex || 'N/A'}`, 350, 150)
        .text(`Date: ${new Date().toLocaleDateString()}`, 50, 170)
        .moveDown();
      
      // Assessment Results
      doc.fillColor('#000000')
        .fontSize(14)
        .text('Assessment Results', 50, 200)
        .fontSize(10);
      
      // Risk Level
      const riskLevel = assessmentData.risk_level || 'Unknown';
      let riskColor = '#000000';
      if (riskLevel.toLowerCase().includes('low')) riskColor = '#4CAF50';
      else if (riskLevel.toLowerCase().includes('moderate')) riskColor = '#FF9800';
      else if (riskLevel.toLowerCase().includes('high') || riskLevel.toLowerCase().includes('emergency')) riskColor = '#f44336';
      
      doc.fillColor(riskColor)
        .text(`Risk Level: ${riskLevel}`, 50, 220)
        .fillColor('#000000');
      
      // AI Reasoning
      if (assessmentData.reason) {
        doc.text('AI Reasoning:', 50, 240)
          .text(assessmentData.reason, 50, 255, { width: 500, align: 'justify' });
      }
      
      // Possible Conditions
      if (assessmentData.possible_conditions && assessmentData.possible_conditions.length > 0) {
        let yPos = 290;
        doc.text('Possible Conditions:', 50, yPos);
        yPos += 15;
        
        assessmentData.possible_conditions.forEach((condition, index) => {
          const confidence = Math.round((condition.confidence || 0) * 100);
          doc.text(`${index + 1}. ${condition.disease} (${confidence}%)`, 60, yPos);
          yPos += 15;
        });
        
        yPos += 10;
      }
      
      // Recommendations
      if (assessmentData.recommendations && assessmentData.recommendations.length > 0) {
        let yPos = 350;
        doc.text('Recommendations:', 50, yPos);
        yPos += 15;
        
        assessmentData.recommendations.forEach((rec, index) => {
          doc.text(`${index + 1}. ${rec}`, 60, yPos, { width: 500, align: 'justify' });
          yPos += 15;
        });
        
        yPos += 10;
      }
      
      // Emergency Notice
      if (riskLevel.toLowerCase().includes('high') || riskLevel.toLowerCase().includes('emergency')) {
        doc.fillColor('#f44336')
          .fontSize(12)
          .text('EMERGENCY NOTICE', 50, 450)
          .fontSize(10)
          .text('Please seek immediate medical attention. Do not delay in consulting a healthcare professional.', 50, 470, { width: 500, align: 'justify' })
          .fillColor('#000000');
      }
      
      // Footer
      doc.fillColor('#666666')
        .fontSize(8)
        .text('This report is generated by MedAid AI system and should not replace professional medical consultation.', 50, 700, { width: 500, align: 'center' })
        .text('For any medical emergency, please contact your local healthcare provider immediately.', 50, 715, { width: 500, align: 'center' })
        .text('Page 1 of 1', 50, 750);
      
      // Finalize PDF file
      doc.end();
      
    } catch (error) {
      reject(error);
    }
  });
};