# Generated by Django 5.2.4 on 2026-01-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_user_role_patientassignment_cliniciannote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="triagerecord",
            name="follow_up_answers",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="triagerecord",
            name="follow_up_questions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="triagerecord",
            name="needs_follow_up",
            field=models.BooleanField(default=False),
        ),
    ]
